#! /bin/sh

#erl -noinput -pa ./_build/default/lib/cecho/ebin ./_build/default/lib/eddy/ebin -s eddy start -s init stop
erl -noinput -pa ./_build/default/lib/cecho/ebin ./_build/default/lib/eddy/ebin -s eddy start

