#! /bin/sh

#erl -noinput -pa ../eddy/_build/default/lib/cecho/ebin ../eddy/_build/default/lib/eddy/ebin -s eddy start -s init stop
erl -noinput -pa ../eddy/_build/default/lib/cecho/ebin ../eddy/_build/default/lib/eddy/ebin -s eddy start

